import localFont from "next/font/local";
import "@/styles/globals.css";
import "@/styles/reset.css"

const montserrat = localFont({
  src: "../assets/fonts/Montserrat-VariableFont_wght.ttf",
  weight: "100 900",
});

export const metadata = {
  title: "FAQ",
  description: "Generated by create next app",
  icons: {
    icon: '/logo.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        {children}
      </body>
    </html>
  );
}
